CREATE TABLE [dbo].[tbUnit](
	[UnitID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](250) NULL,
	[Description] [nvarchar](250) NULL,
	[Show] [bit] NOT NULL CONSTRAINT [DF_tbUnit_Show]  DEFAULT ((1)),
 CONSTRAINT [PK_tbUnit] PRIMARY KEY CLUSTERED 
(
	[UnitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET IDENTITY_INSERT tbUnit ON
Insert into TBUNIT ("UnitID","Name","Description","Show") values (1,'Eid Clothes for Kids','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (2,'Bottle',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (3,'Support Tree',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (4,'THE ISLAMIC CHARITY CENTER- JORDON',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (5,'WAKFET AL RAFAA- LEBANON',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (6,'THE MERCY ASSOCIATION FOR CHILDREN- GAZA',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (7,'CROYDON FC',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (8,'7 DVDs Package',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (9,'SURREY FC',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (10,'TOGDHEER - EAST LONDON',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (11,'Norbury Park FC',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (12,'Blank',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (13,'Team Taqwa',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (14,'TAZ NORTH LONDON',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (15,'LUTON KAM',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (16,'luton kam',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (17,'Bravehearts',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (18,'MASJID REJECTS',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (19,'FRIDAY NIGHT FOOTBALL CLUB',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (20,'South London Mauritian Team',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (21,'WIZEGUYZ',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (22,'Gown Stars',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (23,'Beckenham FC',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (24,'Gold Team',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (25,'Gold Team',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (26,'Team Maldives',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (27,'Englefield Slough FC',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (28,'FRIDAY NIGHT FOOTBALL',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (29,'KKB PROPERTY AND FINANCIAL SERVICES',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (30,'Boca Seniors',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (31,'H&M',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (32,'KKB PROPERTY AND FINANCIAL SERVICES 2',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (33,'The Elite',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (34,'?',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (35,'Wimbledon',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (36,'MORDEN ISLAMIC CENTER',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (37,'Upton Lea',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (38,'Blank',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (39,'A-Team',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (40,'MWA Itehaad FC',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (41,'MWA Itehaad Allstars',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (42,'Liberties',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (43,'Norbury Rejects FC',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (44,'Eastside Heats',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (45,'ALeaf Windows',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (46,'Al-Muntada Team',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (47,'Osborne United',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (48,'EIC FC',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (49,'STREATHAM',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (50,'Poplar',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (54,'Ticket',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (56,'Item',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (57,'3 items for £1',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (58,'Zesyb''s fun patrol','East London Football team','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (59,'KHALIDS BOYS','KHALID-NORTH LONDON','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (60,'Ummah Tigers','Central London Team','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (61,'Hizbullah','West London Team','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (62,'Maaziz London',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (63,'Maaziz London','London','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (64,'SLS STREET','EAST LONDON-FAHEEM','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (65,'ELBOWS OUT',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (66,'QM','ELONDON AQIB','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (67,'JUST MUSLIM','E LONDON MANI','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (68,'EIC',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (69,'QHEIBAR','EAST LONDON AKIM','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (70,'ELBOWS OUT',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (71,'SHAPLA','ESSEXS','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (72,'Belarus','Stoke newington','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (73,'African Camps','West London','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (74,'Forgintina B',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (75,'GLADSTONE PARK RANGERS','WEST LONDON','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (76,'£15 Collective Iftars','£15 will feed 6 people during Collective Iftars','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (77,'£25 Food Parcel','£25 will buy a Ramadan food parcel','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (78,'£30 ''Eid gifts','£30 will buy ''Eid gifts for 4 orphans and needy chdildren','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (79,'£100 Ramadan Sponsorship','£100 will sponsor 2 families in Ramadan','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (80,'Support Interpal''s Ramadan Programme','Support Interpal''s Ramadan Programme','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (81,'Fidya/ Kafarah (per day)','Expeation for not fasting (per day)','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (82,'£25 School Kits','Supporting the education programme by providing school kits','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (83,'£50 Supporting needy students','Financial aid to needy students','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (84,'Community Development Projects','Community Development Projects','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (85,'Educational Projects',' Educational Projects','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (86,'Medical Aid Projects','Medical Aid Projects','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (88,'Sponsor 2 families in Ramadan','Sponsor 2 families in Ramadan','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (89,'Waqf /Sadaqah Jariyah Projects','Waqf /Sadaqah Jariyah Projects','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (90,'Where Most Needed','Where Most Needed','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (91,'Water Tank','£75.00 Water Tank','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (92,'Emergency Gaza Flood Appeal',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (93,'Food Parcel for a needy family','(including 2kg of meat)','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (94,'Eid Present for 50 needy children','Eid Present for 50 needy children','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (95,'Blankets and Clothing',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (96,'Wheel Chair',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (97,'Sponsor Family',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (98,'Tent',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (99,'Contribution towards an ambulance',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (100,'Adult Ticket','Adult £15','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (101,'Child Ticket','Child £10','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (102,'Sadaqah Jariyah Projects for Re-building mosques and schools','Sadaqah Jariyah Projects for Re-building mosques and schools','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (103,'Sakhara Olive Oil','bottle','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (104,'Pre Fab Housing',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (105,'Building Reconstruction','Homes/mosques/hospitals/schools','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (106,'Gaza Cup Sponsorship',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (107,'Al Aqsa Charity Cup Sponsorship','Business sponsorship','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (108,'Al-Aqsa Mosque Projects',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (109,'Water Tank project',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (110,'Charity Football Match For Gaza','Charity Football Match For Gaza','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (111,'Gaza 100 Run','Gaza 100 Run','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (112,'Donation To Convay','Donation To Convay','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (113,'Special Medical Supplies','Special Medical Supplies','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (114,'Wheel Chair','Wheel Chair','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (115,'Islamic Society Rafah','Islamic Society Rafah','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (116,'Fidya',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (117,'Collective iftar',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (118,'Food Parcel',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (119,'Sponsor two families',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (120,'school kit',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (121,'Sponsor student',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (122,'Mini Bus',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (123,'Ticket','Sister''s Iftaar 09','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (124,'Mobility Scooters',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (125,'Share in building a mosque',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (126,'1/6th share of a Prefab home',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (127,'School Materials',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (128,'£5 per day',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (129,'Eid Gifts for 4 needy / orphan children','£30','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (130,'Food Parcel','Includes 2kg of meat','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (132,'Financial Aid','Zakat and sadaqa','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (133,'Winter Package','clothes, blankets, fuel for heaters etc','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (134,'1/7 share of a cow in Palestine','1/7 share of a cow in Palestine','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (135,'1/7 share of a cow in Jordan or Lebanon','1/7 share of a cow in Jordan or Lebanon','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (136,'Sheep in Palestine','Sheep in Palestine','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (137,'Sheep in Jordan or Lebanon','Sheep in Jordan or Lebanon','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (138,'Standard Qurbani','Standard Qurbani','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (139,'20 miles 4 Gaza',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (140,'Community Development','Pre-fab housing, blocks housing, mosques, rents, Maintenance','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (141,'Water Projects','Digging a well, water sorage units, tanks, treatment plant','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (142,'Health and Medical','Heart-Lung machine, medical equipment, medical supplies','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (143,'Education','Rebuilding labs, sponsoring students, Re-equipping','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (144,'Urgent needs',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (145,'Alternative Accommodation for 1 family',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (146,'Clothes, Furniture and blankets',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (147,'Food Package for 1Family',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (148,'Team registration entry',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (149,'Business sponsorship',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (150,'Charity dinner tickets',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (151,'Charity dinner table for 12',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (152,'20 miles 4 Gaza-Brothers only','20 miles 4 Gaza-Brothers only','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (153,'Entry ticket','al-aqsa charity cup','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (154,'Food parcel including 2kg of meat','Food parcel including 2kg of meat','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (155,'Charity dinner tickets Bradford','Charity dinner tickets Bradford','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (156,'Stretchers','Stretchers','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (157,'Incubators','Incubators','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (158,'Ambulance','Ambulance','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (159,'General Medical Fund','General Medical Fund','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (160,'Frame','Charity Dinner Frames','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (161,'Incubators',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (162,'Stretchers',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (163,'Medical supplies',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (164,'Reconstruction materials',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (165,'School supplies',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (166,'Food',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (167,'Large Box',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (168,'Zakat al-Fitr',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (169,'Large Public Tank (For hospitals, mosques or schools)','For hospitals, mosques or schools','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (170,'Family Water Tank (250 litres)',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (171,'Have a date with us – Ramadan Charity Iftar','Ramadan 2010','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (172,'Collective Iftar','Feeds 6 people, in Ramadan','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (173,'Food Parcel','1 Family feeds 6-8 people','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (174,'Sponsor 2 Families','Includes Food parcels, Iftar & possibly cash assistance depending on needs of family. Feeds 8-10.','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (175,'Zakat Al-Fitr','Towards needy families: food/cash assistance','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (176,'Fidya','Per meal, feeds 1 person during Ramadan.
Although this should reflect individual status','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (177,'Eid Gifts for 4 needy children','New Clothes & toys for children and widows','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (178,'Bread Bag For Family/Day','Essential for a Palestinian diet','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (179,'School Kit','School Bag, Stationary kit and 3 dozens exercise books','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (180,'Sponsor a Child for a Term','Provides costs for necessary equipment and transport','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (181,'Educational Materials for School','Money spent on repair of building, transportation of students; i.e. school bus, laboratories as well as extensive assistance for the learning difficulties','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (182,'Female Uniform','Provides conservative and modest school uniform','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (183,'Male Uniform','Provides conservative and modest school uniform.','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (184,'1 Month Water Supply for Family','Provides 1 month of safe & clean water supply','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (185,'1 Month Water Supply for Public Place','Fills 1 month supply of water for a public place','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (187,'Paramedic Motorbike','Provides rapid emergency response to unforeseen events','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (188,'Infant Incubator','Provides a special ‘womb-like’ environment for new born or premature infants','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (189,'1 Month Fuel Supply','Supplies one month fuel supply for the hospitals and medical transportation','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (190,'Essential Medicine','Particularly needed to provide up to at least 114 essential medications, currently out of stock in GAZA','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (191,'Ambulance Stretcher','1 Stretcher','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (192,'1 emergency Gas Light','Essential for emergency transportation','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (193,'Cash assistance for a needy family',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (194,'Eid Gift for a poor family/children',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (195,'Food parcel including 2kg of meat',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (196,'Qurbani Project General Aid',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (197,'1 kilo of meat',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (198,'(size: S)',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (199,'(size: M)',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (200,'(size: L)',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (201,'(size: XL)',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (202,'Rebuilding Mosques',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (203,'Rebuilding Schools',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (204,'Rebuilding Hospitals',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (205,'Bradford charity dinner','Dec 2010','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (206,'(size: YL)',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (207,'20 mile walk registration fee',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (208,'Leicester charity dinner---Adults','April 2011','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (209,'Leicester charity dinner---Children (Under 12)','April 2011','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (210,'Leicester charity dinner---Family/Friends Table of 10','April 2011','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (211,'Essential medicine',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (212,'Medical equipments',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (213,'Mobile ambulance',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (214,'Where most needed',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (215,'Galactomin 19 Formula (for GGM sufferers)',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (216,'Nutramigen Infant Formula (for lactose intolerance)',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (217,'Food Parcel',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (218,'Collective Iftaar',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (219,'Zakatul-Fitr',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (220,'Eid Gifts',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (221,'Sponsor a Family',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (222,'Water Tank',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (223,'Collective Iftar',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (224,'University Fees',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (225,'Family Water Tank',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (226,'fdfdf','fdfdf','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (227,'Medicines and Treatment Costs',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (228,'Fidya',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (229,'Kaffarah',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (230,'Infant milk formula',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (231,'Medical equipments',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (232,'Charity Iftar ticket: Leicester',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (233,'Charity Iftar ticket: Bradford',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (234,'Charity Iftar ticket: London',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (235,'Charity Iftar ticket: Manchester',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (236,'Charity Iftar ticket: Birmingham',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (237,'Eid in Park Bradford',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (238,'Financial Assistance - Zakat',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (239,'Eid Gift Package',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (240,'Food Parcel (including 2kgs of meat)',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (241,'Fresh meat package (containing 2kg fresh meat)',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (242,'Palestine Large Animal',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (243,'Palestine Small Animal',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (244,'Lebanon Large Animal',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (245,'Lebanon Small Animal',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (246,'Jordan  Large Animal',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (247,'Jordan Small Animal',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (248,'Interpal Qurbani',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (249,'Seeds',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (250,'PHD 21.04.2012',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (251,'School uniform',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (252,'School kit',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (253,'Eid gifts',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (254,'Collective Iftar per head (Iftar + Suhoor)','Collective Iftar for disadvantaged children and orphans- 5 pounds per head (1 meal)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (255,'Infant milk formula',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (256,'University fee support',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (257,'Collective Iftars',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (258,'Water public tank','Water public tank','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (259,'Water public tank refill','Water public tank refill','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (260,'Financial Assistance',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (261,'Water family tank','Water Tank- 40 pounds per family','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (262,'Water family tank refill','Water- 10 pounds per monthly refill','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (263,'Food parcels','Food parcels- 50 pounds (family of 6)','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (264,'Kaffarah',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (265,'Fidya',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (266,'Infant incubator',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (267,'Sponsorship',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (268,'Medicines and treatment costs',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (269,'Share to build apartments',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (270,'Share for the poor patient fund',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (271,'Public water tank refill',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (272,'Zakatul-Fitr',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (273,'Gifts for 10 kids',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (274,'Gift for a family (-+ 8)',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (275,'Package',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (276,'Event for the 500 children',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (277,'School uniform + Kit',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (278,'General Donation',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (279,'Standard Qurbani',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (280,'Jordan Large Animal',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (281,'Jordan Large Animal',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (282,'Palestine Large Animal',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (283,'Sheep in Lebanon',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (284,'Sheep in Jordan',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (285,'Small animal in Palestine',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (290,'Eid gift package(s) at £35 each',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (291,'2Kg fresh meat package(s) at £15 each',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (292,'Food parcel(s), with 2kg meat, at £25 each',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (294,'General hospital support fund','Gaza Emergency 2012','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (295,'Injured persons fund','Gaza Emergency 2012','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (296,'Where most needed','Gaza Emergency Aid 2012','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (297,'Surgical treatment package','Gaza Emergency Aid 2012','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (298,'Medical Aid to hospitals','Gaza Emergency Aid 2012','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (299,'Emergency package for families','Gaza Emergency Aid 2012','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (300,'Medical Aid to Hospital(s)','Gaza Rebuilding Campaign','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (301,'Injured Patients Fund','Gaza Rebuilding Campaign','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (302,'Shelter a Family','Gaza Rebuilding Campaign','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (303,'Home Damage Repairs','Gaza Rebuilding Campaign','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (304,'Blankets for a Family','Gaza Rebuilding Campaign','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (305,'Heater for a Home','Gaza Rebuilding Campaign','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (306,'Agricultural projects','Gaza Rebuilding Campaign','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (307,'Where Most Needed','Gaza Rebuilding Campaign','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (308,' Water Project','Raise for Life Birmingham','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (309,'Water tanker','Water Project','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (310,'PSYCOSOCAIL SUPPORT FOR CHILDREN',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (311,'Palestine: Journey Through The Ages Ticket','FR event','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (312,'Palestine: Journey Through The Ages Limited Child Discount!',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (313,'PalJourney Event Stall',null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (315,'Life saving Medicine','Chance To live','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (316,'Psychosocial support for children','Chance to Live','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (317,'Essential treatment for poor patients','Chance to live','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (318,'Hospital running costs','Chance to live','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (319,'Medical professional training','Chance to live','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (320,'One month supply of life-saving  baby milk formula','Chance to live','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (321,'Health clinic generator','Chance to live','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (322,'Construction of essential healthcare facilities','Chance to live','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (323,'Where most needed','Chance To Live','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (324,'Ticket £30',null,'true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (326,'Support for Syrian Refugees','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (327,'Eid Gifts for Kids','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (329,'Eid Gift for a Family','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (330,'Emergency Aid','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (331,'School Kit (Education Aid)','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (332,'University Fees (Education Aid)','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (340,'Financial Aid (Zakat)','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (341,'Ramadan Check- ups','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (342,'Essential Medicines/ Medical Projects','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (343,'Water Tanks (west bank)','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (347,'Eid Clothes for Kids','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (349,'Financial Aid (Zakat)','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (350,'Support a tree','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (351,'Ambulance stretcher','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (353,'Large Public Water Tanks','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (356,null,null,'false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (357,'Water Coolers','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (358,'Water (General)','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (359,'water refill (west bank)','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (360,'Large public water tank refill','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (365,'Families water tank','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (366,'Families Water Tank Refil','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (367,'Infant Milk Formula','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (368,'Water Tanker (delivery vehicle)','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (370,'Generator','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (371,'administration and delivery costs','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (372,'Medical Equipment','Chance To Live','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (373,'Bread Distribution','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (377,'General Medical Aid','Medical Aid','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (379,'General Food Aid','Food Aid','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (380,'General Water Aid','Water Aid','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (381,'General Agriculture Aid','Agriculture Aid','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (382,'Where Most Needed','Where Most Needed','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (383,'where most needed (ramadan)','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (385,'Iftar for 10 needy people','Live Appeal 1 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (386,'Food for one family for the whole of Ramadan','Live Appeal 1 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (387,'Water Aid Large water tank','Live Appeal 1 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (389,'Medical Aid: Poor Patient Fund','Live Appeal 1 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (390,'Financial Aid 20 refugee families','Live Appeal 1 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (391,'Financial Aid','Ramadan refugee 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (392,'Job Creation','Community Development','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (393,'Water Aid','Live Appeal 2 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (394,'Medical Aid','Live Appeal 2 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (395,'Food Aid','Live Appeal 2 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (396,'Zakat Distribution','Live Appeal 2 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (397,'Special infant milk formula','Live Appeal 3 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (398,'One year support for a child','Live Appeal 3 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (399,'10 Children with Eid gifts and school kits','Live Appeal 3 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (400,'Public water tank for school and one year water supply','Live Appeal 3 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (401,'Children''s welfare centre','Live Appeal 3 (Ramadan)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (402,'Poor Patient Fund','Ramadan- Refugees','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (403,'Religious Education Projects','Children of Palestine','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (404,'School Kit','Back 2 School 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (405,'School Uniform','Back 2 School 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (406,'University Fee Support','Back 2 School 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (407,'School Equipment','Back 2 School 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (408,'Computer Labs','Back 2 School 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (409,'Qurbani','Eid Al Adha 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (410,'2kg Meat Package','Eid Al Adha 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (411,'Non-meat food parcel','Eid Al Adha 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (412,'Eid Gift','Eid Al Adha 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (413,'Small Animal Palestine','Eid Al Adha 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (414,'1/7 Cow Palestine','Eid Al Adha 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (415,'Small Animal Jordan & Lebanon','Eid Al Adha 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (416,'1/7 Cow Jordan & Lebanon','Eid Al Adha 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (417,'Interpal Qurbani','Qurbani live appeal 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (418,'Eid Gifts','Qurbani live appeal 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (419,'Food Aid: Fresh Meat for 10 families','Qurbani live appeal 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (420,'Eid Joy Package','Qurbani live appeal 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (421,'West Bank small animal','Qurbani live appeal 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (422,'West Bank 1/7 share large animal','Qurbani live appeal 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (423,'Jordan / Lebanon small animal','Qurbani live appeal 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (424,'Jordan / Lebanon 1/7 share of large animal','Qurbani live appeal 2013','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (425,'Jumbo Dates 1kg','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (426,'Medium Dates 1kg','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (427,'Olive Oil 500ml','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (428,'Olive Oil 750ml','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (429,'Zaatar','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (430,'Black Seed Oil','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (431,'Blackseed Paste','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (432,'Chilli Sauce','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (433,'Maramiya','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (434,'Freeka','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (435,'Food Parcel','GPU Food Parcel','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (436,'Towards Food Parcel','GPU Food Parcel','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (437,'Olive Tree','GPU Olive Tree','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (438,'Towards Olive Tree','GPU Olive Tree','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (439,'Blanket','Winter Aid 2014','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (440,'Child Clothes','Winter Aid 2014','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (441,'Home Heater','Winter Aid 2014','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (442,'Fuel (1 month)','Winter Aid 2014','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (443,'Financial Aid','Winter Aid 2014','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (444,'Food Parcel','Winter Aid 2014','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (445,'General Donation','Winter Aid 2014','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (446,'Blanket','Emergency Live Appeal (Winter Aid 2014)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (447,'Child Clothes','Emergency Live Appeal (Winter Aid 2014)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (448,'Home Heater','Emergency Live Appeal (Winter Aid 2014)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (449,'Fuel (1 month)','Emergency Live Appeal (Winter Aid 2014)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (450,'Financial Aid','Emergency Live Appeal (Winter Aid 2014)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (451,'Food Parcel','Emergency Live Appeal (Winter Aid 2014)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (452,'General Donation','Emergency Live Appeal (Winter Aid 2014)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (453,'One Family Supply','Emergency Live Appeal (Winter Aid 2014)','false');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (455,'Where most needed','Refugee Crisis','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (456,'Financial Aid','Refugee Crisis','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (457,'Food Parcel','Refugee Crisis','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (458,'Zakat','Refugee Crisis','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (459,'General Donation','Refugee Crisis','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (460,'Yarmouk Refugee Camp','Refugee Crisis','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (461,'Early Bird','Nakba Tickets','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (462,'Standard','Nakba Tickets','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (463,'Table of 10','Nakba Tickets','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (464,'Sumac','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (465,'Discount Ticket','Nakba Tickets','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (466,'Weekend Offer','Nakba Tickets','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (467,'Family Water Tank','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (468,'Family Water Refill','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (469,'Public Water Tank','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (471,'Public Water Tank Refill','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (472,'Water Cooler','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (473,'Water Projects','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (474,'Food Parcel','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (475,'Infant Milk Formula','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (476,'Infant Incubator','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (477,'Financial Aid (Zakat)','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (478,'Support for Syrian Refugees','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (479,'Support a family (1 year)','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (481,'Psychosocial support for children','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (482,'School kit','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (483,'School uniform','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (484,'University fees','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (485,'Rebuilding Gaza','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (486,'Community development','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (487,'Help with administration costs','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (488,'Poor patient fund','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (489,'General medical fund','Refugee Relief','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (490,'Food Aid','Nakbah LA 2014','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (491,'Water Aid','Nakbah LA 2014','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (492,'Emergency Medical Aid','Nakbah LA 2014','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (493,'10 Food Parcels','Nakbah LA 2014','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (494,'Financial Aid (10 families)','Nakbah LA 2014','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (495,'Financial Aid (20 families)','Nakbah LA 2014','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (496,'Fidya','Fidya & Kaffarah','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (497,'Kaffarah','Fidya & Kaffarah','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (498,'Financial Aid','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (499,'Zakat Ul-Fitir','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (500,'Fidya','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (501,'Kaffarah','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (503,'Family Water Tank','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (504,'Family Water Tank Refill','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (505,'Water Tank','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (506,'Water Tank Refill','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (507,'Public Water Tank','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (508,'Public Water Tank Refill','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (509,'School Kit','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (510,'School Uniform','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (511,'Food Aid','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (512,'Medical Aid','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (513,'Where Most Needed','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (514,'Iftar (hot meal)','Feeding Futures','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (515,'Water Tank + 1 Year Supply','Welcoming Ramadan LA','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (516,'Food Parcels (10 Families)','Welcoming Ramadan LA','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (517,'Financial Aid (10 Families)','Welcoming Ramadan LA','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (518,'200 Meals','Welcoming Ramadan LA','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (519,'Food & Financial Aid (20 Families)','Welcoming Ramadan LA','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (520,'Fidya','Welcoming Ramadan LA','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (521,'Kaffarah','Welcoming Ramadan LA','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (522,'Zakat-Ul-Fitr','Welcoming Ramadan LA','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (523,'Delivery (£6.50)','Interpal E-store','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (524,'Refugee relief family package','Ramadan LA 2','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (525,'Urgent medical aid','Ramadan LA 2','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (526,'Feed the hungry','Ramadan LA 2','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (527,'Financial aid','Ramadan LA 2','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (528,'Where needed most','Ramadan LA 2','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (529,'Admin','Ramadan LA 2','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (530,'Fidyah','Ramadan LA 2','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (531,'Kaffarah','Ramadan LA 2','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (532,'Zakatul-fitr','Ramadan LA 2','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (533,'Donation for Gaza','Alhiwar Liveappeal','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (534,'Plant a Tree','Radio Live Appeal','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (535,'Eid Gifts','Radio Live Appeal','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (536,'Water Refill','Radio Live Appeal','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (537,'Food Parcel','Radio Live Appeal','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (538,'Financial Aid for Family','Radio Live Appeal','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (539,'Water Tank + 1 year water','Radio Live Appeal','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (540,'Medical Aid','Radio Live Appeal','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (541,'Iftar Meals 60 people','Radio Live Appeal','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (542,'Financial Aid 10 Families','Radio Live Appeal','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (543,'Where Most Needed','Radio Live Appeal','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (544,'Child Sponsorship','Child Sponsorship','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (545,'Urgent Medical Aid','Ramadan LA 3','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (546,'Trauma Support for Children & Families','Ramadan LA 3','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (547,'Water Aid','Ramadan LA 3','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (548,'Emergency Family Relief','Ramadan LA 3','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (549,'Shelter Support','Ramadan LA 3','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (550,'Where Most Needed','Ramadan LA 3','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (551,'Fidya','Ramadan LA 3','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (552,'Kaffarah','Ramadan LA 3','true');
Insert into TBUNIT ("UnitID","Name","Description","Show") values (553,'Zakatul Fitr','Ramadan LA 3','true');


SET IDENTITY_INSERT tbUnit OFF